version: "3.7"

networks:
  gql_net:

services:
  gql_server:
    build: 
      context: ./server/
    container_name: "gql_server"
    networks:
      - gql_net
    ports:
      - 8080:8080
    volumes:
      - /home/node/app/
      - ./server/:/home/node/app/server/

      # Bounded contexts
      - ./home/:/root/app/home/
      - /root/app/home/client/elm-stuff/

    command:
      - /bin/sh
      - -c
      - |
        cd /root/app/

        echo "Setting up /root/app/..."

        echo "Setting up the homepage..."

        cd /root/app/home/client/
        make watch

        cd /root/app/
        echo "Done."

  #gql_client:
  #  build: 
  #    context: ./client/
  #  container_name: "gql_client"
  #  environment:
  #    - ELM_HOME=/root/.elm
  #  volumes:
  #    - /root/app
  #    - /root/app/elm-stuff/

  #    # Bounded contexts
  #    - ./home/:/root/app/home/
  #    - /root/app/home/client/elm-stuff/
  #  command:
  #    - /bin/sh
  #    - -c
  #    - |
  #      echo "TODO: Setup the client..."
